const express = require('express');
const router  = express.Router();

module.exports = (db) => {
  router.post("/", (req, res) => {
    console.log('this order ===>', req.body)
    const order = req.body;
    if (order.cphone.length !== 10) {
        const templateVars = {
            script: 'Oops! Please resubmit your order and enter a valid phone number at checkout to finalise. We await you. Thank you!'
        }
        res.render('index', templateVars)
    } else {
        let phone = order.cphone;
        let name = order.cname
        let orderf = JSON.parse(order.order);
        let clientText = '';
        console.log(orderf); //==================
        let qstring1 = `INSERT INTO orders (
            menu_items,   -- ARRAY OF ARRAYS [[1,2,3],[2,3,4]] -> [[item_id, qnty, unit_price]]
            item_names,
            customer_name ,
            customer_phone ,
            total_paid ,
            start_time ,
            end_time
          )
          VALUES
          ('$1-js-a' , '$2-js-a' , $3, $4 , '$5-js-a', '$6-js-a','$7-js-a'); -- -js-a = js automated, meaning the value that goes there will be generated by js from the client input form plus...`
    }
    const templateVars = {
        script: 'Thank you for your order! \nCheck your SMS for estimated time to pickup.'
    }
    res.render('index', templateVars)

    // const queryString = `
    // SELECT * 
    // FROM menu_dishes;
    // `;
  
    // db.query(queryString)
    //   .then(data => {
    //     const menus = data.rows;
    //     const menuVar= {menus};
    //     res.render("menus_show", menuVar);
    //   })
    //   .catch(err => {
    //     res
    //       .status(500)
    //       .json({ error: err.message });
    //   });
   
  });
  return router;
};